# Generated by Django 4.2.6 on 2023-12-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='plant_images/')),
                ('water_last', models.DateField()),
                ('water_cycle', models.IntegerField()),
                ('fertilizer_last', models.DateField()),
                ('fertilizer_cycle', models.IntegerField()),
            ],
        ),
    ]
